### PR TITLE
Update read_pns.R

### PR DESCRIPTION
**Pull request by djalmabarbosa**
Erros de digitação?

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
As a maintainer of the package, I inform you that there was no typo in the read_pns function, we only use specific pipes from the magrittr package like %<>% and %$% for determinated procedures that differs from the usual pipe %>% suggested in the correction.

Translate: Como mantenedor do pacote, informo que não houve erro de digitação na função read_pns, só usamos pipes específicos do pacote magrittr como %<>% e %$% para procedimentos determinados que diferem do pipe usual %>% sugerido na correção.

Reference: https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html

**Comment by djalmabarbosa** [comment]
Ok! Thanks for explaining. 
Sorry for any inconvenience.

**Comment by djalmabarbosa** [comment]
Thanks for explaining

**Pull request closed without merging**
